apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: pod-watcher
deploy:
  kubectl:
    manifests:
      - manifest/rbac.yaml
      - manifest/deployment.yaml
      - examples/busybox-good.yaml
      - manifest/mailhog.yaml
      - examples/busybox-bad.yaml
